### ISSUE TITLE
pdfx.sty:  error No color profile found to use for RGB screen colors..

### ISSUE THREAD

**Issue by benevidesh** [Grupo-de-Estudos-em-Logica-da-UFRN/Para-Todxs-Natal#3]
Ao compilar localmente, o compilador retorna o erro descrito acima. Ele aponta para a linha `1303` do arquivo `pdfx.sty`, mas nada muito informativo se encontra ali.

Mais alguem com o mesmo problema?

**Comment by Rhalah** [comment]
Oi, Hudson!
Estava com o mesmo erro, mas como o pdf era gerado mesmo assim, fui deixando pra lá.
O problema foi resolvido quando instalei o pacote icc-profiles na minha distribuição Linux, como informado aqui:
https://tex.stackexchange.com/questions/380798/no-color-profile-found-to-use-for-rgb-screen-colors

**Comment by benevidesh** [comment]
@Rhalah valeu pelo retorno. Acessei o link. Parece ser isso mesmo que você descreveu. Minha distro não disponibiliza esse pacote.

Resolvi removendo o arquivo `pdfx.sty`.  Funcionando perfeitamente agora.
