### ISSUE TITLE
pdfx.sty: error Undefined control sequence.

### ISSUE THREAD

**Issue by benevidesh** [Grupo-de-Estudos-em-Logica-da-UFRN/Para-Todxs-Natal#4]
Problema retornado pelo compilador ao usar o arquivo `forallxyyc.tex`. Aponta para a linha `1802` do arquivo `pdfx.sty`, onde encontramos:

```tex
 \pdfx@xmpmarkup
```

**Comment by Rhalah** [comment]
O problema ainda ocorre ao se resolver o erro levantado no issue 3?
Aqui não está dando nenhum erro¹.

¹ Warning e badbox tem vários. :'-D

**Comment by benevidesh** [comment]
Resolvido, depois da sugestão para issue #3
