### ISSUE TITLE
No capítulo "Argumentos", a introdução perdeu o sentido da ambiguidade em inglês

### ISSUE THREAD

**Issue by Rhalah** [Grupo-de-Estudos-em-Logica-da-UFRN/Para-Todxs-Natal#5]
Em inglês "Argument" tem o sentido de uma discussão acalorada, uma disputa verbal ou quase briga.
Os autores diferenciaram esse sentido do usado no livro, mas em português não há essa ambiguidade.

**Comment by Rhalah** [comment]
@danieldurantepa já corrigiu esse ponto, confere?
Vou começar a ir limpando aqui os issues.

**Comment by danieldurantepa** [comment]
Sim, isso já foi corrigido. Os Capítulos 1 e 2 na versão atual ficaram bem “distantes “ do forallx.

**Comment by Rhalah** [comment]
Show.
Fechando o issue.
